[package]
name = "koshi-image"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
flate2.workspace = true
image = { workspace = true, features = ["bmp", "gif", "jpeg", "png", "tiff", "webp"] }
serde = { workspace = true, features = ["rc"] }
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
