[package]
name = "koshi-observability"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
koshi-core = { version = "0.4.0-pr.1", path = "../koshi-core" }
koshi-paths = { version = "0.4.0-pr.1", path = "../koshi-paths" }
tracing.workspace = true
tracing-subscriber = { version = "0.3.23", features = ["json"] }
