[package]
name = "koshi-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
koshi-config = { version = "0.1.0", path = "../koshi-config" }
koshi-core = { version = "0.1.0", path = "../koshi-core" }
koshi-observability = { version = "0.1.0", path = "../koshi-observability" }
koshi-renderer = { version = "0.1.0", path = "../koshi-renderer" }
ratatui = { version = "0.30.2", default-features = false }
