//! Tab command handlers: create, close, rename, focus, and reorder.

use super::*;

impl Runtime {
    /// Resolve a tab-addressed command ([`Command::CloseTab`],
    /// [`Command::RenameTab`], [`Command::MoveTab`]): the explicit `tab`
    /// argument, else the source's active tab, together with the owning
    /// session borrowed mutably.
    fn acting_tab_session(
        &mut self,
        tab: Option<TabId>,
        source: &CommandSource,
    ) -> Result<(TabId, &mut Session), Rejection> {
        let acting = self.acting_session(source)?;
        let tab_id = self.resolve_tab_or_active(tab, source, acting)?;
        let session_id = acting
            .map(|session| session.id)
            .ok_or_else(|| Rejection::bare(RejectReason::TargetNotFound))?;
        let session = self
            .sessions
            .get_mut(&session_id)
            .ok_or_else(|| Rejection::bare(RejectReason::TargetNotFound))?;
        Ok((tab_id, session))
    }

    /// Handle [`Command::NewTab`]: create a tab holding one fresh shell pane
    /// and switch the designated client onto it, in launch-then-commit order —
    /// no session state changes until the child process is live.
    ///
    /// The designated client — an explicit `--client` target (which wins even
    /// over the issuer, and rejects outright if not attached), else the
    /// in-session issuer, else the session's sole attached client — provides
    /// the viewport the root pane is sized against, and is the only client
    /// whose view moves. The tab's name is generated by
    /// [`koshi_core::naming::generate_name`] avoiding the session's existing
    /// tab names — the caller supplies none.
    /// The root pane runs the default shell in `--cwd`. After the
    /// commit, the tab the client left reflows to its remaining viewers'
    /// viewport; a tab left with no viewer keeps its sizes. A launch failure
    /// commits nothing and rejects, so a tab never exists without its
    /// process.
    pub(super) fn handle_new_tab(
        &mut self,
        command_id: CommandId,
        source: &CommandSource,
        args: &NewTabArgs,
        issued_at: SystemTime,
    ) -> Result<CommandResult, Rejection> {
        let acting = self.acting_session(source)?;
        let target = Self::resolve_new_tab_target(args, source, acting)?;
        // Clone the shared backend before borrowing a session: spawn then
        // needs no `&self` borrow, so it coexists with `&mut Session`.
        let backend = Arc::clone(self.pty_backend());
        let pane_min = self.effective_pane_min();
        // The root pane runs the default shell carrying `--cwd`. Built before the
        // session is borrowed so it can read the terminal config off `self`.
        let spawn_spec = self.default_shell_spec(args.cwd.clone(), BTreeMap::new());

        let session = self
            .sessions
            .get_mut(&target.session_id)
            .ok_or_else(|| Rejection::bare(RejectReason::TargetNotFound))?;
        let client = session
            .clients
            .get(target.client_id)
            .ok_or_else(|| Rejection::bare(RejectReason::SourceClientStale))?;

        // New tab occupies the client's middle pane region, excluding chrome.
        let viewport = pane_viewport(client.viewport());
        let new_pane_id = PaneId::new();
        let new_tab_id = TabId::new();
        let candidate = LayoutNode::Pane(new_pane_id);
        let tab_rect = Rect::new(Point { x: 0, y: 0 }, viewport);
        if !fits(&candidate, tab_rect, pane_min) {
            return Err(Rejection::new(
                RejectReason::MinSize,
                "not enough space for a new tab",
            ));
        }
        let spawn_size = size_root_pane(new_pane_id, viewport, pane_min);

        // Resolve the tab's name before the spawn: a generated one no
        // existing tab in the session already uses.
        let name = generate_name(NameKind::Tab, |candidate| {
            session.tabs.values().any(|tab| tab.name() == candidate)
        });

        let launch_cwd = spawn_spec.cwd.clone();

        // Launch the child BEFORE committing any state. On failure nothing
        // was registered and no view moved, so the command rejects as if it
        // never ran.
        let handle = Self::spawn_child(backend.as_ref(), new_pane_id, spawn_spec, spawn_size)?;

        // The child is live — commit all session state through the pure op:
        // it registers the root pane `Running`, appends the tab, and switches
        // the designated client onto it. It returns the client's previous
        // tab, for the reflow below.
        let spec = NewPaneSpec {
            cwd: launch_cwd,
            command: None,
        };
        let (prev_tab, mut events) = tab_ops::commit_new_tab(
            session,
            new_tab_id,
            new_pane_id,
            name,
            Some(target.client_id),
            spec,
            issued_at,
        );

        // Park the handle so a forwarder relays its output/exit, and record its
        // size so later reflows can tell whether a resize is a real change. The
        // terminal engine gives the child's output a grid to land in.
        self.park_pane_pty(new_pane_id, handle, spawn_size);
        // Announce the new pane's size — PaneCreated carries none.
        events.push(Event::PtyResized(PtyResized {
            pane_id: new_pane_id,
            size: spawn_size,
        }));

        // The client left its previous tab; if that tab still has a viewer,
        // reflow its live panes to the viewport it now sizes against. A tab
        // left with no viewer has no viewport and keeps its sizes.
        if let Some(prev_tab) = prev_tab {
            self.reflow_tab_if_viewed(backend.as_ref(), target.session_id, prev_tab, &mut events);
        }

        Ok(Self::commit_events(command_id, events))
    }

    /// Handle [`Command::CloseTab`]: tear the tab and every pane in it out of
    /// the session and kill their children, in commit-then-kill order — the
    /// state removal is authoritative and immediate, the kills are
    /// best-effort and off-thread.
    ///
    /// Close policies gate the whole tab up front, all-or-nothing: without
    /// `--force`, one `ConfirmIfBusy` pane whose child has not provably
    /// exited rejects the close before anything mutates, with a hint at
    /// `--force`. `--force` force-kills every pane regardless of policy. The
    /// removal itself is [`tab_ops::close_tab`]: pane records drop, the tab
    /// goes, viewers move to the nearest surviving tab, and closing the last
    /// tab quits the session. The kills run on one detached thread per pane —
    /// a graceful kill sleeps out its grace window, so every child gets its
    /// stop request immediately and the dispatcher never stalls.
    ///
    /// After the removal, the tab the displaced viewers landed on reflows to
    /// its new viewport (it now counts the movers). A destination with no
    /// viewer — or a close that quit the session — reflows nothing.
    pub(super) fn handle_close_tab(
        &mut self,
        command_id: CommandId,
        source: &CommandSource,
        args: &CloseTabArgs,
    ) -> Result<CommandResult, Rejection> {
        // Clone the shared backend before borrowing a session: the kill
        // thread takes its own handle, so no `&self` borrow crosses the
        // commit.
        let backend = Arc::clone(self.pty_backend());

        let (tab_id, session) = self.acting_tab_session(args.tab, source)?;
        let session_id = session.id;
        let tab = session
            .tabs
            .get(&tab_id)
            .ok_or_else(|| Rejection::bare(RejectReason::TargetNotFound))?;
        let pane_ids = tab.layout().leaf_panes();

        // Pick how every child dies before anything mutates — all-or-nothing:
        // one busy `ConfirmIfBusy` pane rejects the whole tab.
        let mut kills: Vec<(PaneId, KillPolicy)> = Vec::with_capacity(pane_ids.len());
        for &pane_id in &pane_ids {
            let Some(record) = session.panes.get(pane_id) else {
                continue;
            };
            let kill_policy = Self::pick_kill_policy(
                record,
                args.force,
                args.tree,
                "a pane in the tab may be busy; pass --force to close anyway",
            )?;
            kills.push((pane_id, kill_policy));
        }

        // Commit the state removal: pane records drop, the tab goes, viewers
        // move to the nearest surviving tab, last-tab close quits the session.
        let mut events = tab_ops::close_tab(session, tab_id);

        // The panes are gone from state; drop their runtime bookkeeping — PTY
        // handle, size cache, terminal engine, scroll offsets, and highlights. Keyed
        // off the layout's own leaf list — the exact set the op removed.
        for &pane_id in &pane_ids {
            self.release_pane_bookkeeping(session_id, pane_id);
        }

        // Displaced viewers landed on the nearest surviving tab (the
        // cascade's `TabFocused`); its viewport now counts them, so it
        // reflows. A destination with no viewport keeps its sizes.
        let destination = events.iter().find_map(|event| match event {
            Event::TabFocused(focused) => Some(focused.tab_id),
            _ => None,
        });
        if let Some(destination) = destination {
            self.reflow_tab_if_viewed(backend.as_ref(), session_id, destination, &mut events);
        }

        // Kill the children off-thread: a graceful kill sleeps out its grace
        // window, and the dispatcher must keep draining. One thread per pane
        // so every child receives its stop request immediately; each kill
        // also purges the backend's own entry for its pane.
        for (pane_id, kill_policy) in kills {
            let backend = Arc::clone(&backend);
            let _ = thread::spawn(move || {
                let _ = backend.kill(pane_id, kill_policy);
            });
        }

        Ok(Self::commit_events(command_id, events))
    }

    /// Handle [`Command::RenameTab`]: update the tab's display name.
    ///
    /// The caller supplies no name — a gimmick name is drawn from
    /// [`generate_name`], skipping every name already on one of the
    /// session's tabs (including the target's current one, so the rename
    /// always changes it). The rename applies through
    /// [`tab_ops::rename_tab`]. Names resolve nothing, so layout, focus,
    /// and PTYs are untouched.
    pub(super) fn handle_rename_tab(
        &mut self,
        command_id: CommandId,
        source: &CommandSource,
        args: &RenameTabArgs,
    ) -> Result<CommandResult, Rejection> {
        let (tab_id, session) = self.acting_tab_session(args.tab, source)?;
        let new_name = generate_name(NameKind::Tab, |candidate| {
            session.tabs.values().any(|tab| tab.name() == candidate)
        });

        let events = tab_ops::rename_tab(session, tab_id, new_name);

        Ok(Self::commit_events(command_id, events))
    }

    /// Handle [`Command::FocusTab`]: switch the designated client's view to
    /// the target tab.
    ///
    /// The target client — an explicit `--client` (which wins even over the
    /// issuer, and rejects outright if not attached), else the issuer, else
    /// the session's sole attached client — switches to the tab the resolver
    /// named; `next`/`prev` wrap the display order relative to that client's
    /// active tab. Re-focusing the already-active tab is a clean no-op with
    /// no events. After the switch both affected tabs reflow: the target tab
    /// now counts the arriving viewer and the left tab no longer does; a tab
    /// left with no viewer keeps its sizes. A rejected focus mutates nothing.
    pub(super) fn handle_focus_tab(
        &mut self,
        command_id: CommandId,
        source: &CommandSource,
        args: &FocusTabArgs,
    ) -> Result<CommandResult, Rejection> {
        let acting = self.acting_session(source)?;
        let target = Self::resolve_focus_tab_target(args, source, acting)?;

        let backend = Arc::clone(self.pty_backend());

        let session = self
            .sessions
            .get_mut(&target.session_id)
            .ok_or_else(|| Rejection::bare(RejectReason::TargetNotFound))?;
        let client = session
            .clients
            .get(target.client_id)
            .ok_or_else(|| Rejection::bare(RejectReason::SourceClientStale))?;
        let prior_tab = client.active_tab();

        // Already viewing it — nothing to do, and no events: events are
        // completed facts.
        if prior_tab == target.tab_id {
            return Ok(TransactionScope::new().commit(command_id));
        }

        let mut events = tab_ops::focus_tab(
            session,
            target.client_id,
            tab_ops::TabTarget::Id(target.tab_id),
        );

        // Both tabs' viewer sets changed: the target tab gained the arriving
        // viewer, the left tab lost it. Reflow each that still has a viewer;
        // a tab with no viewer has no viewport and keeps its sizes.
        for tab_id in [target.tab_id, prior_tab] {
            self.reflow_tab_if_viewed(backend.as_ref(), target.session_id, tab_id, &mut events);
        }

        Ok(Self::commit_events(command_id, events))
    }

    /// Handle [`Command::MoveTab`]: reorder the target tab to a new display
    /// slot within its session.
    ///
    /// The target tab — an explicit `--tab`, else the issuing pane's tab for
    /// the in-session CLI, else the issuer's active tab — moves to the
    /// requested zero-based index, clamped to the valid range, and the other
    /// tabs close ranks around it. Display order is the only thing that
    /// changes: which tab each client views, layout, focus, and PTYs are all
    /// untouched. Moving a tab to the slot it already occupies is a clean
    /// no-op with no events. A rejected move mutates nothing.
    pub(super) fn handle_move_tab(
        &mut self,
        command_id: CommandId,
        source: &CommandSource,
        args: &MoveTabArgs,
    ) -> Result<CommandResult, Rejection> {
        let (tab_id, session) = self.acting_tab_session(args.tab, source)?;

        let events = tab_ops::move_tab(session, tab_id, args.index);

        Ok(Self::commit_events(command_id, events))
    }
}
