//! Tab command handlers: create, close, focus, and reorder.

use super::*;

impl Server {
    /// Resolve a tab-addressed command ([`Command::CloseTab`],
    /// [`Command::MoveTab`]) to its tab and the owning session, borrowed
    /// mutably.
    ///
    /// The tab is [`Self::resolve_tab_or_active`]: the explicit `tab_id`
    /// argument, else the tab holding the issuing pane for an in-session CLI,
    /// else the acting client's active tab.
    ///
    /// Rejects with [`RejectReason::TargetNotFound`] when the command source names no
    /// live session, the issuing pane is gone, or the tab is gone;
    /// [`RejectReason::SourceClientStale`] when the command source's client is no
    /// longer attached; [`RejectReason::TargetAmbiguous`] when several clients
    /// are attached and none is named.
    fn resolve_acting_tab_session(
        &mut self,
        requested_tab_id: Option<TabId>,
        command_source: &CommandSource,
    ) -> Result<(TabId, &mut Session), Rejection> {
        let resolve_acting_session = self.resolve_acting_session(command_source)?;
        let tab_id =
            self.resolve_tab_or_active(requested_tab_id, command_source, resolve_acting_session)?;
        let session_id = resolve_acting_session
            .map(|session| session.session_id)
            .ok_or_else(|| Rejection::from_reason(RejectReason::TargetNotFound))?;
        let session = self
            .session_by_id
            .get_mut(&session_id)
            .ok_or_else(|| Rejection::from_reason(RejectReason::TargetNotFound))?;
        Ok((tab_id, session))
    }

    /// Handle [`Command::NewTab`]: create a tab holding one fresh shell pane
    /// and switch the designated client onto it, in launch-then-commit order —
    /// no session state changes until the child process is live.
    ///
    /// The designated client — an explicit `--client` target (which wins even
    /// over the issuer, and rejects outright if not attached), else the
    /// issuer while it is still attached, else the session's sole attached
    /// client — provides the viewport the root pane is sized against, and is
    /// the only client whose view moves. The tab's name is generated by
    /// [`koshi_core::naming::generate_name`] avoiding the session's existing
    /// tab names — the caller supplies none.
    /// The root pane runs the default shell in the requested directory,
    /// else where the designated client's focused pane currently is
    /// ([`Self::resolve_pane_working_directory`]). After the
    /// commit, the tab the client left reflows to its remaining viewers'
    /// viewport; a tab left with no viewer keeps its sizes. A designated
    /// client reporting [`PaneArea::Starving`], and a pane area too small to
    /// hold one pane, are both rejected with [`RejectReason::MinSize`] and
    /// the hint `"not enough space for a new tab"`. A launch failure commits
    /// nothing and rejects, so a tab never exists without its process.
    pub(super) fn handle_new_tab(
        &mut self,
        command_id: CommandId,
        command_source: &CommandSource,
        command_args: &NewTabArgs,
        issued_at: SystemTime,
    ) -> Result<CommandResult, Rejection> {
        let resolve_acting_session = self.resolve_acting_session(command_source)?;
        let tab_target =
            Self::resolve_new_tab_target(command_args, command_source, resolve_acting_session)?;
        // An owned handle on the shared backend. The spawn below uses it while
        // the session is borrowed mutably.
        let pty_backend = Arc::clone(self.get_pty_backend());
        let pane_sizing = self.get_pane_sizing();
        // The root pane runs the default shell in the requested directory.
        // Built before the session is borrowed, reading `self.config.terminal`.
        let mut spawn_spec =
            self.build_default_shell_spec(command_args.working_directory.clone(), BTreeMap::new());
        // No directory was asked for: the tab opens where the designated
        // client's focused pane currently is ([`Self::resolve_pane_working_directory`]).
        if spawn_spec.working_directory.is_none() {
            spawn_spec.working_directory = self
                .session_by_id
                .get(&tab_target.session_id)
                .and_then(|session| session.clients.get_client_by_id(tab_target.client_id))
                .and_then(|client| client.get_focused_pane(client.get_active_tab()))
                .and_then(|pane_id| {
                    self.resolve_pane_working_directory(tab_target.session_id, pane_id)
                });
        }

        let session = self
            .session_by_id
            .get_mut(&tab_target.session_id)
            .ok_or_else(|| Rejection::from_reason(RejectReason::TargetNotFound))?;
        let client = session
            .clients
            .get_client_by_id(tab_target.client_id)
            .ok_or_else(|| Rejection::from_reason(RejectReason::SourceClientStale))?;

        // The new tab fills the designated client's pane area.
        let reject_when_no_room = || {
            Rejection::from_reason_and_help(RejectReason::MinSize, "not enough space for a new tab")
        };
        let designated_pane_area = client.get_pane_area().ok_or_else(reject_when_no_room)?;
        let new_pane_id = PaneId::new();
        let new_tab_id = TabId::new();
        let tab_rect = Rect::from_size_at_origin(designated_pane_area);
        if !is_layout_within_rect(&LayoutNode::Pane(new_pane_id), tab_rect, pane_sizing) {
            return Err(reject_when_no_room());
        }
        let new_tab_pty_size =
            compute_root_pane_pty_size(new_pane_id, designated_pane_area, pane_sizing);

        // Resolve the tab's name before the spawn: a generated one no
        // existing tab in the session already uses.
        let tab_name = generate_name(NameKind::Tab, |candidate_tab_name| {
            session
                .tabs
                .values()
                .any(|tab| tab.get_tab_name() == candidate_tab_name)
        });

        let launch_working_directory = spawn_spec.working_directory.clone();
        spawn_spec
            .environment_variables
            .extend(build_koshi_environment(
                tab_target.session_id,
                Some(tab_target.client_id),
                new_pane_id,
                koshi_paths::resolve_runtime_directory().as_deref(),
            ));

        // Launch the child BEFORE committing any state. A failure returns
        // here with nothing registered and no view moved.
        let child_handle = Self::spawn_child(
            pty_backend.as_ref(),
            new_pane_id,
            spawn_spec,
            new_tab_pty_size,
        )?;

        // The child is live — commit all session state through the pure op:
        // it registers the root pane `Running`, appends the tab, and switches
        // the designated client onto it. It returns the client's previous
        // tab, for the reflow below.
        let new_pane_spec = NewPaneSpec {
            working_directory: launch_working_directory,
            spawn_spec: None,
        };
        let (previous_tab_id, mut emitted_events) = tab_ops::commit_new_tab(
            session,
            new_tab_id,
            new_pane_id,
            tab_name,
            Some(tab_target.client_id),
            new_pane_spec,
            issued_at,
        );

        // Park the handle: a forwarder relays its output and exit, the spawn
        // size lands in the size cache later reflows compare against, and the
        // terminal engine gives the child's output a grid to land in.
        self.park_pane_pty(new_pane_id, child_handle, new_tab_pty_size);
        // Announce the new pane's size — PaneCreated carries none.
        emitted_events.push(Event::PtyResized(PtyResized {
            pane_id: new_pane_id,
            pty_size: new_tab_pty_size,
        }));

        // The client left its previous tab; if that tab still has a viewer,
        // reflow its live panes to the viewport it now sizes against. A tab
        // left with no viewer has no viewport and keeps its sizes.
        if let Some(previous_tab_id) = previous_tab_id {
            self.reflow_tab_if_viewed(
                pty_backend.as_ref(),
                tab_target.session_id,
                previous_tab_id,
                &mut emitted_events,
            );
        }

        Ok(Self::commit_events(
            &mut self.event_bus,
            command_id,
            emitted_events,
        ))
    }

    /// Handle [`Command::CloseTab`]: tear the tab and every pane in it out of
    /// the session and kill their children, in commit-then-kill order — the
    /// state removal is authoritative and immediate, the kills are
    /// best-effort and off-thread.
    ///
    /// Close policies gate the whole tab up front, all-or-nothing: without
    /// `--force`, one `ConfirmIfBusy` pane whose child has not provably
    /// exited rejects the close before anything mutates, with a hint at
    /// `--force`. `--force` force-kills every pane regardless of policy.
    /// `--tree` widens each picked kill to the child's whole process group,
    /// and still lets a busy `ConfirmIfBusy` pane reject the close. The
    /// removal itself is [`tab_ops::close_tab`]: pane records drop, the tab
    /// goes, viewers move to the nearest surviving tab, and closing the last
    /// tab quits the session. The kills run on one detached thread per pane —
    /// a graceful kill can sleep out its grace window, every child gets its
    /// stop request immediately, and the dispatcher keeps draining.
    ///
    /// After the removal, the tab the displaced viewers landed on reflows to
    /// its new viewport (it now counts the movers). A destination with no
    /// viewer — or a close that quit the session — reflows nothing.
    pub(super) fn handle_close_tab(
        &mut self,
        command_id: CommandId,
        command_source: &CommandSource,
        command_args: &CloseTabArgs,
    ) -> Result<CommandResult, Rejection> {
        // An owned handle on the shared backend. Each kill thread takes its own
        // clone of it, and no `&self` borrow crosses the commit below.
        let pty_backend = Arc::clone(self.get_pty_backend());

        let (tab_id, session) =
            self.resolve_acting_tab_session(command_args.tab_id, command_source)?;
        let session_id = session.session_id;
        let target_tab_state = session
            .tabs
            .get(&tab_id)
            .ok_or_else(|| Rejection::from_reason(RejectReason::TargetNotFound))?;
        let pane_ids = target_tab_state.get_layout_tree().list_leaf_pane_ids();

        // Pick how every child dies before anything mutates — all-or-nothing:
        // one busy `ConfirmIfBusy` pane rejects the whole tab.
        let mut pane_kill_policies: Vec<(PaneId, KillPolicy)> = Vec::with_capacity(pane_ids.len());
        for &pane_id in &pane_ids {
            let Some(pane_record) = session.panes.get_pane_record_by_id(pane_id) else {
                continue;
            };
            let kill_policy = Self::resolve_pane_kill_policy(
                pane_record,
                command_args.should_force_close,
                command_args.should_kill_process_tree,
                "a pane in the tab may be busy; pass --force to close anyway",
            )?;
            pane_kill_policies.push((pane_id, kill_policy));
        }

        // Commit the state removal: pane records drop, the tab goes, viewers
        // move to the nearest surviving tab, last-tab close quits the session.
        let mut emitted_events = tab_ops::close_tab(session, tab_id);

        // The panes are gone from state; drop their runtime bookkeeping — PTY
        // handle, size cache, terminal engine, scroll offsets, and highlights. Keyed
        // off the layout's own leaf list — the exact set the op removed.
        for &pane_id in &pane_ids {
            self.release_pane_bookkeeping(session_id, pane_id);
        }

        // Displaced viewers landed on the nearest surviving tab (the
        // cascade's `TabFocused`); its viewport now counts them, and it
        // reflows. A destination with no viewport keeps its sizes.
        if let Some(destination_tab_id) = find_first_focused_tab_id(&emitted_events) {
            self.reflow_tab_if_viewed(
                pty_backend.as_ref(),
                session_id,
                destination_tab_id,
                &mut emitted_events,
            );
        }

        // One thread per pane, so every child receives its stop request
        // immediately.
        for (pane_id, kill_policy) in pane_kill_policies {
            super::kill_off_thread(&pty_backend, pane_id, kill_policy);
        }

        Ok(Self::commit_events(
            &mut self.event_bus,
            command_id,
            emitted_events,
        ))
    }

    /// Handle [`Command::FocusTab`]: switch the designated client's view to
    /// the target tab.
    ///
    /// The target client — an explicit `--client` (which wins even over the
    /// issuer, and rejects outright if not attached), else the issuer while
    /// it is still attached, else the session's sole attached client —
    /// switches to the tab the resolver named; `next`/`prev` wrap the display
    /// order relative to that client's active tab. Re-focusing the
    /// already-active tab is a clean no-op with no events. After the switch
    /// both affected tabs reflow: the target tab now counts the arriving
    /// viewer and the left tab no longer does; a tab left with no viewer
    /// keeps its sizes. A rejected focus mutates nothing.
    pub(super) fn handle_focus_tab(
        &mut self,
        command_id: CommandId,
        command_source: &CommandSource,
        command_args: &FocusTabArgs,
    ) -> Result<CommandResult, Rejection> {
        let resolve_acting_session = self.resolve_acting_session(command_source)?;
        let tab_target =
            Self::resolve_focus_tab_target(command_args, command_source, resolve_acting_session)?;

        let pty_backend = Arc::clone(self.get_pty_backend());

        let session = self
            .session_by_id
            .get_mut(&tab_target.session_id)
            .ok_or_else(|| Rejection::from_reason(RejectReason::TargetNotFound))?;
        let client = session
            .clients
            .get_client_by_id(tab_target.client_id)
            .ok_or_else(|| Rejection::from_reason(RejectReason::SourceClientStale))?;
        let prior_tab_id = client.get_active_tab();

        // Already viewing it — nothing to do, and no events: events are
        // completed facts.
        if prior_tab_id == tab_target.tab_id {
            return Ok(TransactionScope::new().commit(command_id, &mut self.event_bus));
        }

        let mut emitted_events = tab_ops::focus_tab(
            session,
            tab_target.client_id,
            tab_ops::TabTarget::Id(tab_target.tab_id),
        );

        // Both tabs' viewer sets changed: the target tab gained the arriving
        // viewer, the left tab lost it. Reflow each that still has a viewer;
        // a tab with no viewer has no viewport and keeps its sizes.
        for tab_id in [tab_target.tab_id, prior_tab_id] {
            self.reflow_tab_if_viewed(
                pty_backend.as_ref(),
                tab_target.session_id,
                tab_id,
                &mut emitted_events,
            );
        }

        Ok(Self::commit_events(
            &mut self.event_bus,
            command_id,
            emitted_events,
        ))
    }

    /// Handle [`Command::MoveTab`]: reorder the target tab to a new display
    /// slot within its session.
    ///
    /// The target tab — an explicit `--tab`, else the issuing pane's tab for
    /// the in-session CLI, else the issuer's active tab — moves to the
    /// requested zero-based index, clamped to the valid range, and the other
    /// tabs close ranks around it. Display order is the only thing that
    /// changes: which tab each client views, layout, focus, and PTYs are all
    /// untouched. Moving a tab to the slot it already occupies is a clean
    /// no-op with no events. A rejected move mutates nothing.
    pub(super) fn handle_move_tab(
        &mut self,
        command_id: CommandId,
        command_source: &CommandSource,
        command_args: &MoveTabArgs,
    ) -> Result<CommandResult, Rejection> {
        let (tab_id, session) =
            self.resolve_acting_tab_session(command_args.tab_id, command_source)?;

        let emitted_events = tab_ops::move_tab(session, tab_id, command_args.target_tab_index);

        Ok(Self::commit_events(
            &mut self.event_bus,
            command_id,
            emitted_events,
        ))
    }
}
