[package]
name = "koshi-kitty"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64 = "0.23.1"
flate2 = { version = "1.1.9", default-features = false, features = ["rust_backend"] }
koshi-image = { version = "0.4.0", path = "../koshi-image" }
libc.workspace = true
thiserror = "2.0.18"

[dev-dependencies]
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_System_Memory",
    "Win32_System_SystemInformation",
] }
