[package]
name = "koshi-terminal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
percent-encoding = "2.3.2"
thiserror.workspace = true
koshi-core = { version = "0.4.0-pr.1", path = "../koshi-core" }
unicode-segmentation = "1.13.3"
unicode-width = "0.2.2"
vte = { version = "0.15.0", default-features = false }
serde = { workspace = true, features = ["rc"] }
image = { version = "0.25.10", default-features = false, features = ["bmp", "gif", "jpeg", "png", "tiff", "webp"] }
flate2 = { version = "1.1.9", default-features = false, features = ["rust_backend"] }
base64 = "0.23.1"

[dev-dependencies]
serde_json.workspace = true
