[package]
name = "koshi-terminal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
image.workspace = true
koshi-core.workspace = true
koshi-image.workspace = true
koshi-iterm.workspace = true
koshi-kitty.workspace = true
koshi-sixel.workspace = true
percent-encoding.workspace = true
serde = { workspace = true, features = ["rc"] }
unicode-segmentation.workspace = true
unicode-width.workspace = true
vte.workspace = true

[dev-dependencies]
base64.workspace = true
flate2.workspace = true
serde_json.workspace = true
