[package]
name = "koshi-terminal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
percent-encoding = "2.3.2"
thiserror.workspace = true
koshi-core = { version = "0.4.0-pr.1", path = "../koshi-core" }
unicode-segmentation = "1.13.3"
unicode-width = "0.2.2"
vte = { version = "0.15.0", default-features = false }
serde = { workspace = true, features = ["rc"] }

[dev-dependencies]
serde_json.workspace = true
