[package]
name = "koshi-test-support"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
koshi-core = { version = "0.3.0-pr.3", path = "../koshi-core" }
koshi-ipc = { version = "0.3.0-pr.3", path = "../koshi-ipc" }
koshi-pty = { version = "0.3.0-pr.3", path = "../koshi-pty" }
tempfile.workspace = true
